---
- name: Create the directories
  loop:
    - "{{ config_dir }}/fish"
    - "{{ config_dir }}/fish/functions"
    - "{{ config_dir }}/fish/conf.d"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy the fish configuration files
  with_fileglob: "files/*.fish"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/fish/{{ item | basename }}"
    owner: "{{ username }}"
    mode: 0755

- name: Template the fish configuration templates
  with_fileglob: "templates/*.fish"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/fish/{{ item | basename }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy the fish functions
  with_fileglob: "files/functions/*.fish"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/fish/functions/{{ item | basename }}"
    state: link

# - name: Deploy the BW session key
#   ansible.builtin.template:
#     src: "conf.d/bw_session.fish"
#     dest: "{{ ansible_env.HOME }}/{{ config_dir }}/fish/conf.d/bw_session.fish"
#     owner: "{{ username }}"
#     mode: 0644
