#! /usr/bin/env ansible-playbook -c dotfiles/ansible.cfg
---
- name: Install applications and configure dotfiles
  hosts: macs
  gather_facts: yes
  become: no
  roles:
    - role: system
      tags:
        - system

    # - role: fish
    #   tags:
    #     - fish

    # - role: geerlingguy.mac.mas
    #   tags:
    #     - mac-app-store

    # - role: geerlingguy.mac.dock
    #   tags:
    #     - dock

    - role: geerlingguy.mac.homebrew
      tags:
        - homebrew

    - role: gantsign.oh-my-zsh
      tags:
        - zsh

    - role: zsh
      tags:
        - zsh

    - role: tmux
      tags:
        - tmux

    - role: karabiner
      tags:
        - karabiner

    - role: kitty
      tags:
        - kitty

    - role: neofetch
      tags:
        - neofetch

    - role: vscode
      tags:
        - vscode
