---
roles:
    # mac specific roles
    - name: gantsign.oh-my-zsh

    # linux specific roles
    - name: geerlingguy.security
    - name: geerlingguy.docker
    - name: geerlingguy.ntp
    - name: geerlingguy.pip

collections:
    # mac specific collections
  - name: geerlingguy.mac