# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
  
    config.vm.box = "geerlingguy/ubuntu1804"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrent", disabled: true
  
    config.vm.provider :docker do |d|
      d.build_dir = "."
      d.remains_running = true
      d.has_ssh = true
   end
  
    # # app server 1
    # config.vm.define "app1" do |app|
    #   app.vm.hostname = "orc-app1.test"
    #   app.vm.network :private_network, ip: "192.168.33.14"
    # end
  
    # # db server 3
    # config.vm.define "db" do |db|
    #   db.vm.hostname = "orc-db.test"
    #   db.vm.network :private_network, ip: "192.168.33.15"
    # end
  
  end
  