---
- name: Update and upgrade packages 
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: root
    env: yes
    job: ""
