---

- name: Create personal directories
  loop:
    - ".config"
    - "{{ home_dir }}/development"
    - "{{ home_dir }}/development/refs"
    - "{{ home_dir }}/personal"
    - "{{ home_dir }}/admin"
    - "{{ home_dir }}/media"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ username }}"
    mode: 0755
