---

- name: Setup system packages
  block:
  - name: Update and upgrade packages 
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes

  - name: Install Packages for Enterprise Linux
    include_role:
      name: geerlingguy.repo-epel
    when: ansible_facts['os_family']|lower == 'redhat'

  - name: Install Extra Packages
    package:
      name: "{{ extra_packages }}"
      state: present

- name: Setup hostnames
  when: testing_environment is undefined
  block:
    - name: Set the hostname
      hostname:
        name: "{{ inventory_hostname }}"
        use: "systemd"

    - name: Replace the hostname entry with our own
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: ^127\.0\.0\.1 *localhost
        line: "127.0.0.1 {{ inventory_hostname }}"
        owner: root
        group: root
        mode: '0644'

- name: Configure system 
  block:
  - name: Disable cron e-mail notifications
    when: testing_environment is undefined
    become: true
    cron:
      name: MAILTO
      user: root
      env: yes
      job: ""
