---
- name: Setup user and permissions
  block:
    - name: Set the name of a sudo group
      set_fact:
        sudo_group: sudo

    - name: Ensure the necessary groupsexists
      loop:
        - "{{ username }}"
        - docker
      group:
        name: "{{ item }}"
        state: present

    - name: Create a login user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        groups: 
          - "{{ sudo_group }}"
          - docker
          - users
        state: present
        append: true

    - name: Allow '{{ sudo_group }}' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ sudo_group }}'
        line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    
    - name: Copy the public SSH key 
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_public_key }}"

    - name: Chmod the user home directory
      file:
        path: "/home/{{ username }}"
        state: directory
        mode: 0755
        owner: "{{ username }}"
        group: "{{ username }}"
        recurse: yes

- name: User preferences
  block:
    - name: Set the default shell
      user: 
        name: "{{ username }}"
        shell: "{{ shell }}"

    # - name: Create group directories
    #   loop: "{{ config_dir | zip( directories | flatten ) }}"
    #   ansible.builtin.file:
    #     state: directory
    #     path: "{{ ansible_env.HOME }}/{{ config_dir }}"
    #     owner: "{{ username }}"
    #     mode: 0755

    - name: Create personal directories
      loop: "{{ directories }}"
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_env.HOME }}/{{ item }}"
        owner: "{{ username }}"
        mode: 0755

    # - name: Disable fish greeting
    #   lineinfile:
    #     path: /home/{{ username }}/.config/fish/fish_variables
    #     state: present
    #     regexp: 'fish_greeting:.+'
    #     line: 'SETUVAR fish_greeting:'
    #     create: true
    #     owner: "{{ username }}"
    #     group: "{{ username }}"
    #     mode: 0644
    #   when: '"fish" in shell'

    - name: Suppress login messages
      file:
        name: /home/{{ username }}/.hushlogin
        mode: 0644
        state: touch
        owner: "{{ username }}"
        group: "{{ username }}"
        modification_time: preserve
        access_time: preserve