---
- name: Create the directories
  loop:
    - ".config/zsh"
    - ".config/zsh/functions"
    - ".config/zsh/conf.d"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ username }}"
    mode: 0755

- name: Deploy the zsh files
  with_fileglob: "files/*.zsh"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/zsh/{{ item | basename }}"
    state: link

- name: Add configs to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "ZSH_CUSTOM={{ ansible_env.HOME }}/.config/zsh/"
    state: present
    backup: yes