---
- name: Create the zsh directory
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/zsh"
    owner: "{{ username }}"
    mode: 0755

- name: Template zsh files
  with_fileglob: "files/*.zsh"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/zsh/{{ item | basename }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy the zsh files
  with_fileglob: "files/*.zsh"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/zsh/{{ item | basename }}"
    owner: "{{ username }}"
    mode: 0755

- name: Add config folder to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "ZSH_CUSTOM={{ ansible_env.HOME }}/.config/zsh/"
    state: present
    backup: yes

