---
- name: Make sure that the karabiner config folder is created
  loop:
    - karabiner
    - karabiner/assets
    - karabiner/assets/complex_modifications
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ config_dir }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Copy the karabiner asset files
  with_fileglob: "files/assets/complex_modifications/*.json"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/karabiner/assets/complex_modifications/{{ item | basename }}"
    owner: "{{ username }}"
    mode: "0755"

- name: Copy the karabiner asset files
  ansible.builtin.copy:
    src: "files/karabiner.json"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/karabiner/karabiner.json"
    owner: "{{ username }}"
    mode: "0755"
