---
- name: Make sure that the neofetch config folder is created
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ config_dir }}/neofetch"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Copy the neofetch configuration file in place
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config.conf"
    dest: "{{ ansible_env.HOME }}/{{ config_dir }}/neofetch/config.conf"
    owner: "{{ username }}"
    mode: "0755"
