---

- name: Check if homebrew is installed
  register: system_brew_installed
  changed_when: system_brew_installed.rc > 0 # rc. is part of the command reply 0 is successful
  ansible.builtin.command:
    cmd: brew --version

- name: download iTerm2
  unarchive:
    url: 